import { Inter } from "next/font/google";
import "./globals.css";
import * as React from "react";
import Box from "@mui/material/Box";
import Drawer from "@mui/material/Drawer";
import CssBaseline from "@mui/material/CssBaseline";
import AppBar from "@mui/material/AppBar";
import Toolbar from "@mui/material/Toolbar";
import List from "@mui/material/List";
import Image from "next/image";
import logo from "@/public/logo2.png";
import {
  FaBell,
  FaExpand,
  FaMapMarkerAlt,
  FaRegMoon,
  FaSearch,
  FaSignOutAlt,
  FaUser,
  FaUsers,
} from "react-icons/fa";
import { RiLightbulbFlashFill } from "react-icons/ri";
import { TbBulbFilled } from "react-icons/tb";
import { GiWallet } from "react-icons/gi";
import FormatAlignLeftIcon from "@mui/icons-material/FormatAlignLeft";
import { Button, InputAdornment, TextField } from "@mui/material";
import Profile from "./components/profile/page";

const settings = ["Profile", "Account", "Dashboard", "Logout"];

const drawerWidth = 200;

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className="min-h-screen">
      <body className={inter.className}>
        <Box sx={{ display: "flex" }}>
          <CssBaseline />

          {/* --------------------------------------------------nav */}
          <AppBar
            className="bg-white text-black shadow-none"
            position="fixed"
            sx={{
              width: `calc(100% - ${drawerWidth}px)`,
              ml: `${drawerWidth}px`,
            }}
          >
            <Toolbar>
              <div className="w-full flex justify-between">
                <div className="flex items-center">
                  <span className="pr-5 text-2xl">
                    <FormatAlignLeftIcon />
                  </span>

                  <div>
                    <TextField
                      className="py-2 ml-4"
                      placeholder="Search.."
                      size="small"
                      InputProps={{
                        startAdornment: (
                          <InputAdornment position="start">
                            {" "}
                            <FaSearch />
                          </InputAdornment>
                        ),
                      }}
                    />
                  </div>
                </div>
                <div className=" flex align-middle">
                  <Button className="text-black" size="large">
                    <FaExpand />
                  </Button>
                  <Button className="text-black " size="large">
                    <FaRegMoon />
                  </Button>
                  <Button className="text-black " size="large">
                    <FaBell />
                  </Button>
                  <Profile></Profile>
                  
                </div>
              </div>
            </Toolbar>
          </AppBar>

          {/* ------------------------------------------side drawer------------------------------- */}
          <Drawer
            sx={{
              width: drawerWidth,
              flexShrink: 0,
              "& .MuiDrawer-paper": {
                width: drawerWidth,
                boxSizing: "border-box",
              },
            }}
            variant="permanent"
            anchor="left"
          >
            {/* ministy logo */}
            <div className="h-[70px]  pt-4   flex">
              <Image
                src={logo}
                className="w-[70px] pl-4"
                alt="ministry of power energy and mineral resources bangladesh logo"
              ></Image>
              <p className="text-xs pl-2 font-semibold">
                Ministry of Power Energy & Mineral Resources
              </p>
            </div>

            <Toolbar />

            <List className="pl-6">
              <ul>
                <li className="flex items-center gap-2 mb-4">
                  <FaUser /> <span>Executive</span>
                </li>
                <li className="flex items-center gap-2 mb-4">
                  <RiLightbulbFlashFill /> <span>Utilities</span>
                </li>
                <li className="flex items-center gap-2 mb-4">
                  <FaMapMarkerAlt />
                  <span>Zone</span>
                </li>
                <li className="flex items-center gap-2 mb-4">
                  <TbBulbFilled /> <span>S & D List</span>
                </li>
                <li className="flex items-center gap-2 mb-4">
                  <FaUsers /> <span>Users</span>
                </li>
                <li className="flex items-center gap-2 mb-4">
                  <GiWallet /> <span>All Tickets</span>
                </li>
                <li className="flex items-center gap-2 mb-4 ">
                  <FaSignOutAlt />
                  <span>Logout</span>
                </li>
              </ul>
            </List>
          </Drawer>

          {/* main content */}
          <Box
            className="bg-slate-100"
            component="main"
            sx={{ flexGrow: 1, p: 3 }}
          >
            <Toolbar />
            {children}
          </Box>
        </Box>
      </body>
    </html>
  );
}
